---

- name: update apt repo
  action: apt update-cache=yes cache_valid_time=3600
  sudo: yes

- name: install python mysql bindings
  apt: name=python-mysqldb state=installed

- name: Install apache2 web server and another packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - libapache2-mod-php
    - php-mysql
    - php-curl
    - php-gd
    - php-intl
    - php-pear
    - php-imagick
    - php-imap
    - php-pspell
    - php-recode
    - php-xmlrpc
    - php-xsl
    - php-mcrypt
    - php-common
    - php-cli
  notify: 
  - start apache2

- name: Copy apache2 configuration
  template: src=/etc/ansible/roles/apache2/templates/default.conf dest=/etc/apache2/apache2.conf
  sudo: yes

- name: Copy apache2 port configuretion
  template: src=/etc/ansible/roles/apache2/templates/ports.conf dest=/etc/apache2/ports.conf
  sudo: yes

- name: Copy apache2 configuration default site
  template: src=/etc/ansible/roles/apache2/templates/000-default.conf dest=/etc/apache2/sites-available/000-default.conf
  sudo: yes

- name: Copy apache2 php configuration
  template: src=/etc/ansible/roles/apache2/templates/php.ini dest=/etc/php/7.0/apache2/php.ini
  sudo: yes

- name: Copy apache2 prefork configuration
  template: src=/etc/ansible/roles/apache2/templates/mpm_prefork.conf dest=/etc/apache2/mods-available/mpm_prefork.conf
  sudo: yes

- name: Enable default site
  command: a2ensite 000-default
  sudo: yes

- name: Enable apache2 module mpm_event
  command: a2dismod mpm_event

- name: Enable apache2 module mpm_prefork
  command: a2enmod mpm_prefork

- name: Enable apache2 module php7.0
  command: a2enmod php7.0

- name: Enable apache2 module session
  command: a2enmod session

- name: Enable apache2 module session_cookie
  command: a2enmod session_cookie

- name: Enable apache2 module session_crypto
  command: a2enmod session_crypto

- name: Enable apache2 module setenvif
  command: a2enmod setenvif

- name: Enable apache2 module rewrite
  command: a2enmod rewrite

- name: Enable apache2 module request
  command: a2enmod request

- name: Enable apache2 module ratelimit
  command: a2enmod ratelimit

- name: Enable apache2 module userdir
  command: a2enmod userdir

- name: Enable apache2 module vhost_alias
  command: a2enmod vhost_alias
  notify: restart apache2

- name: Run copy iptables configuration for Apache2_servers
  template: src=/etc/ansible/roles/apache2/files/iptables-apache2 dest=/etc/init.d/iptables
  sudo: yes

- name: Run exec mode for iptables on Apache2_servers
  command: chmod +x /etc/init.d/iptables
  sudo: yes

- name: Run add service iptables configuration on Apache2_servers
  command: update-rc.d iptables defaults
  sudo: yes

- name: Run simlink for iptables service configuration on Apache2_servers
  file: 
    src: /run/systemd/generator.late/iptables.service
    dest: /etc/systemd/system/multi-user.target.wants/iptables.service
    state: link
  sudo: yes

- name: Remove ufw
  command: apt -y remove ufw --purge
  sudo: yes
