---

- name: Download WordPress
  get_url: url=https://wordpress.org/wordpress-4.9.4.tar.gz dest=/var/www/wordpress-4.9.4.tar.gz
  sudo: yes

- name: Extract archive
  command: chdir=/var/www/ /bin/tar xvf wordpress-4.9.4.tar.gz
  sudo: yes

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/wordpress/wp-config.php
  sudo: yes

- name: Create upload folder
  file: path=/var/www/wordpress/wp-content/uploads state=directory mode=0755 owner=www-data

- name: Change ownership of WordPress installation
  file: path=/var/www/ owner=www-data group=www-data state=directory recurse=yes
  sudo: yes
