---
- hosts: Wordpress_sites

- name: Download WordPress
  get_url: url=https://wordpress.org/wordpress-4.9.4.tar.gz dest=/var/www/wordpress-4.9.4.tar.gz
           sha1sum="0e630bf940fd586b10e099cd9195b3e825fb194c"
  sudo: yes

- name: Extract archive
  command: chdir=/var/www/ /bin/tar xvf wordpress-4.9.4.tar.gz
  sudo: yes

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present
  sudo: yes

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='ec2-34-245-137-20.eu-west-1.compute.amazonaws.com' state=present
  sudo: yes

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/
  sudo: yes

- name: Change ownership of WordPress installation
  file: path=/var/www/ owner=www-data group=www-data state=directory recurse=yes
  sudo: yes
