---
- hosts: MySQL_servers

- name: update apt repo
  action: apt update-cache=yes cache_valid_time=3600
  sudo: yes
      
- debconf:
   name: mysql-server
   question: mysql-server/root_password
   vtype: password
   value: "{{ mysql_root_password }}"


- debconf:
   name: mysql-server
   question: mysql-server/root_password_again
   vtype: password
   value: "{{ mysql_root_password }}"

- name: install mysql-server 
  apt name=mysql-server state=present
  sudo: yes

- debconf:
   name: mysql-server
   question: mysql-server/root_password
   vtype: password
   value: "{{ mysql_root_password }}"


- debconf:
   name: mysql-server
   question: mysql-server/root_password_again
   vtype: password
   value: "{{ mysql_root_password }}"

- name: service mysql  
  action: service name=mysql state=started
  sudo: yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/mysql.cnf
  sudo: yes
  notify:
  - start mysql
  sudo: yes

- restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
  sudo: yes
