---

- name: update apt repo
  action: apt update-cache=yes cache_valid_time=3600
  sudo: yes

- name: install python mysql bindings
  apt: name=python-mysqldb state=installed
      
- debconf:
   name: mysql-server
   question: mysql-server/root_password
   vtype: password
   value: "{{ mysql_root_password }}"

- debconf:
   name: mysql-server
   question: mysql-server/root_password_again
   vtype: password
   value: "{{ mysql_root_password }}"

- name: install mysql-server 
  action: apt name=mysql-server state=present
  sudo: yes

- debconf:
   name: mysql-server
   question: mysql-server/root_password
   vtype: password
   value: "{{ mysql_root_password }}"


- debconf:
   name: mysql-server
   question: mysql-server/root_password_again
   vtype: password
   value: "{{ mysql_root_password }}"

- name: Start service mysql  
  action: service name=mysql state=started
  sudo: yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/mysql.cnf
  notify:
  - start mysql
  sudo: yes

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
  sudo: yes

- name: Create WordPress database
  mysql_db: name="{{ wp_db_name }}"
            state=present
            login_user=root
            login_password="{{ mysql_root_password }}"
  sudo: yes

- name: Create WordPress DB user and grant permissions to WordPress DB
  mysql_user: name="{{ wp_db_user }}"
              password="{{ wp_db_password }}"
              priv="{{ wp_db_name }}.*:ALL"
              host="{{ mysql_remote_host_ip }}"
              state=present
              login_user="root"
              login_password="{{ mysql_root_password }}"
  sudo: yes

- name: Copy iptables configuration for MySQL_servers
  template: src=/etc/ansible/roles/mysql/files/iptables-mysql dest=/etc/init.d/iptables
  sudo: yes

- name: Run iptables configuration exec mode for MySQL_servers
  command: chmod +x /etc/init.d/iptables
  sudo: yes

- name: Add iptables service for MySQL_servers
  command: update-rc.d iptables defaults
  sudo: yes

- name: Create symlink iptables service for MySQL_servers
  file:
    src: /run/systemd/generator.late/iptables.service
    dest: /etc/systemd/system/multi-user.target.wants/iptables.service
    state: link
  sudo: yes

- name: Remove ufw
  command: apt -y remove ufw --purge
  sudo: yes

- name: Reboot after iptables configuration MySQL_servers
  command: shutdown -r -t 15
  sudo: yes
